### PR TITLE
Remove the editors note 2022 from the specification per issue #47

### PR DESCRIPTION
**Pull request by swcurran**
See #47 .

Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by dhh1128** [comment]
Hey, Stephen. I don't have a strong opinion about this. I wrote the text that you're proposing to remove, but I did it at the request of some DIF folks who felt like the spec was stale -- not because I felt a compelling need. So I guess I could go either way. Maybe we need input from @bumblefudge ?

KERI went into production last week, but you're still correct about its status in the sense that did:keri is not currently separated from the larger KERI ecosystem as a standalone DID library.

**Comment by TelegramSam** [comment]
I'd be in favor of a more nuanced deprecation notice that focuses on the potential of keri to replace method 1, while noting the utility of method 2.

**Comment by bumblefudge** [comment]
A KERI-Light stand-alone library that has feature parity with DID:peer in Aries usecases would make that nuanced deprecation notice much easier to write without offending any one either side!

**Comment by bumblefudge** [comment]
And before anyone volunteers me, I'm not familiar enough with that use-case or the test vectors to provide the nuance here, hehe

**Comment by swcurran** [comment]
Can we get this discussion going again.  The did:peer spec is (to me) extremely relevant, and there is no (AFAIK) "KERI-lite" equivalent that might be available.  A KERI did method that is intended for public (globally published) DIDs, but I'm not aware of any work towards the use of KERI-based DIDs being used in a peer to peer scenario.  AFAIK, there is nothing to link to.

**Comment by bumblefudge** [comment]
I'm guessing [the IETF internet draft from May of this year](https://weboftrust.github.io/ietf-did-keri/draft-pfeairheller-did-keri.html) isn't the light/peer version you're looking for?

**Pull request merged**
